;;; flymake-lua-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from flymake-lua.el

(autoload 'flymake-lua-load "flymake-lua" nil t)
(register-definition-prefixes "flymake-lua" '("flymake-"))

;;; End of scraped data

(provide 'flymake-lua-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; flymake-lua-autoloads.el ends here
